#!/usr/bin/perl -wT

#Copyright (C) 2004 Susan J. Dridi sdridi@greens.org
#
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

use strict;
use lib qw(LIB);
use Conf;
use HeadFoot;
use DBConnect;
use DateFormats;
use DataCheck;
use CGI;
use CgiErrors;
use CGI::Session;
$CGI::POST_MAX=0;  # no posts
$CGI::DISABLE_UPLOADS = 1;  # no uploads  
$CGI::HEADERS_ONCE = 1;

my $q = new CGI;
my $cookiename = Conf::cookiename();
my $sid = $q->cookie("$cookiename");
my $temp = qw(TEMP);
my $session = new CGI::Session("driver:File", $sid, {Directory=>$temp});
$session->expire('+1h');
my $guid = $session->param('guid');
my $page = $q->url(-relative => 1);

if (! $guid)
	{
	$session->delete();
	$guid = "";
	}

start();

sub start {

my $pid = $q->param('pid');
my $voterkey = $q->param('key');

my $dbh = DBConnect::connectr();

my $sql = qq {select title from irv where pid = ?};
my $title = $dbh->selectrow_array($sql, undef, $pid);

HeadFoot::head($guid, $page);

print "<h3>Ballot Details</h3>\n";

print "<a href=\"irvdetail?pid=$pid\"><b>Details for Election ID: $pid - $title</b></a><br>\n";
print "<a href=\"irvresult?pid=$pid\"><b>View Current Results</b></a><br><br>\n";

print "<b>Ballot Key:</b> $voterkey<br>\n";

print "<ul><li>This is a secret ballot. Nobody knows how you voted.<li>If you want to share this information, you need to remember the voter key and the election ID for this election.<li>The easiest way to do that is to bookmark this page.<li>If you lose this voter key, nobody can retrieve it for you.</ul>\n";

print "<table cellpadding='4'>\n";
print "<tr><th>Candidate</th><th>Type</th><th>Rank</th></tr>\n";

my $sth = $dbh->prepare(qq {select c.cand, c.candtype, i.candrank from cands c, irvvotes i where c.pid = i.pid and c.candid = i.candid and i.pid = ? and i.voterkey = ? order by i.candrank});
$sth->execute($pid, $voterkey);
$sth->bind_columns(\my ($cand, $candtype, $candrank));
while (my $ref = $sth->fetch) {
	if ($candtype == 1)
		{$candtype = "On Ballot";}
	else
		{$candtype = "Write-In";}
	print "<tr><td>$cand</td><td>$candtype</td><td>$candrank</td></tr>\n";
	}
$sth->finish;
$dbh->disconnect;

print "</table>\n";

HeadFoot::foot();

exit();
}
